### ISSUE TITLE
Release a 0.4.0 version?

### ISSUE THREAD

**Issue by Techcable** [wren-lang/wren-cli#108]
Hi! I maintain the [AUR package for wren](https://aur.archlinux.org/packages/wren/). I include the wren cli distribution along with the main wren library.

Could you please release a 0.4.0 version? I can't just download the master branch, because that would break AUR conventions.

Thanks for your time!

**Comment by joshgoebel** [comment]
_This would be great._

I'd just ask that we please discuss/consider a few additional PRs before we release 0.4... If our release cycle is intended to be super slow/deliberate there are a few things (bug fixes, etc) that would *really* be helpful for the [Exercism](https://exercism.io) Wren track I'm building which depends on the CLI.  And we'd **love** it if students could use the official CLI vs needing us to maintain our own fork.

---

> I can't just download the master branch, because that would break AUR conventions.

Pretty sure I've used aur packages that build from a projects master branch... the CLI project is still very young... perhaps a `wren-cli-master` package is needed, or however AUR typically handles that?

**Comment by ryandesign** [comment]
0.4.0 was released nearly two years ago so this should probably be closed.
