### ISSUE TITLE
continue

### ISSUE THREAD

**Issue by pkoppstein** [wren-lang/wren-cli#128]
`continue` is a useful and well-documented Wren feature, but it is not available using the current (very old!) release of wren-cli.

If a new release of the wren-cli is not planned in the near future, what would the simplest alternative be?

**Comment by ruby0x1** [comment]
a new build is planned very soon in fact, though building yourself isn't too much of a detour and is quick if in a hurry.

**Comment by pkoppstein** [comment]
@ruby0x1 - Tx for the quick response.  I tried finding build instructions for making a new wren-cli based on the current wren but had no luck ...

**Comment by ruby0x1** [comment]
here's the steps, it's already updated to wren 0.4, just not the releases. https://github.com/wren-lang/wren-cli/#to-build-the-wren-cli

**Comment by pkoppstein** [comment]
Thanks again.  What wasn't clear was that no extra step is needed to clone or download the latest release of wren itself ....

**Comment by ruby0x1** [comment]
I just setup the CI as I was intending to, you can try the artifacts here which are built from latest: https://github.com/wren-lang/wren-cli/actions/runs/1458483959

**Comment by joshgoebel** [comment]
@pkoppstein Also feel free to check out the Wren CLI that power's all of the Wren [Exercism](https://exercism.org) stuff.  It includes Wren version 0.4 with several library improvements also. There are binaries for all 3 platforms available also in addition to building from source.

- https://github.com/exercism/homebrew-wren
- https://github.com/joshgoebel/wren-console

**Comment by pkoppstein** [comment]
@joshgoebel - Thanks for the heads-up.  Unfortunately, homebrew won't install wren-console on my Mac because my "Xcode (10.1) is too outdated".  Updating Xcode on my computer requires "upgrading" the whole OS, which I am not able to do for various reasons....

**Comment by joshgoebel** [comment]
> but the JSON methods don't seem to be available

They were added after the 0.2.91 release... Every single commit has it's build assets attached though so it's possible that _might_ help you:

https://github.com/joshgoebel/wren-console/actions/runs/1270416831

>  I also couldn't find the code for the JSON module in the repository

The README mentions that much of the library functionality is provided by the [wren-essentials](https://github.com/joshgoebel/wren-essentials) library - which is built-in to wren-console by default.

**Comment by pkoppstein** [comment]
@joshgoebel I was able to upgrade Xcode to 11.3.1 and `brew install wren-console` succeeded!

As for the JSON module -- as best I can tell, the provided methods are not designed to read one JSON entity at a time from a file containing a stream of JSON entities.  What would it take to be able to "load" one JSON entity at a time from a JSONL file, for example?  Or am I missing something?

**Comment by joshgoebel** [comment]
Just read one line at a time yourself and ask JSON to parse each like one at a time.

**Comment by pkoppstein** [comment]
@joshgoebel - Sorry, I wrote JSONL when I actually meant to write stream of JSON that does NOT necessarily conform to the JSONL specification. (E.g. some JSON pretty-printed over several lines.)

**Comment by joshgoebel** [comment]
Same answer, JSON is intended to parse valid single JSON strings... if you think there is a bug with the JSON library in wren-essentials then I'd suggest perhaps opening an issue there vs continuing the discussion here.
