### ISSUE TITLE
Log.info allows only strings

### ISSUE THREAD

**Issue by Kasparsu** [wren-lang/wren-cli#143]
Api allows only strings, but I also get weird behavior when provided with num or well not string where window does not open at all and no error message is provided. If possible might want to add option to provide any type to be logged for debug purposes. 

Platform: Windows

**Comment by mhermier** [comment]
Can you elaborate, show an example of what is not working. AFAIK `Log.info` is not part of `wren` or `wren-cli` so I as this this request looks not valid.

**Comment by Kasparsu** [comment]
Sorry wrong project. Wanted to make this issue under DOME game engine that uses wren. Chuck it up to having too many tabs open. Closing
