### ISSUE TITLE
REPL output is invisible on light-colored terminals

### ISSUE THREAD

**Issue by wasamasa** [wren-lang/wren-cli#16]
This confused me for a good while.

Expected behavior:

```
> var x = 1
> x
1
> System.print(x)
1

>
```

Actual behavior:

```
> var x = 1
> x
 
> System.print(x)
1

>
```

I stared at `repl.wren` for a good while until I noticed that it actually prints the result of evaluating an expression, but in bright white. If your background color is the same, you won't see anything, even if selecting the text (because that swaps foreground and background color which are the same, so no difference).

What's the way forward here? Simply dropping the color escapes for this case to make use of the default foreground color? Introducing a light/dark color scheme? Checking the value type and reusing the built-in associations for picking the right color? Making a function that gives you the printed representation of a value, lexing it and printing it the same way as the input?

**Comment by wasamasa** [comment]
I guess since my PR was closed without any comment and so were all other open ones, keeping this issue open is meaningless.

**Comment by ruby0x1** [comment]
The PR's getting closed was an automated system github has in place, it wasn't intended and doesn't have any meaning.
