### ISSUE TITLE
Wren WriteBytes doesnt Work

### ISSUE THREAD

**Issue by hall-of-code** [wren-lang/wren-cli#50]
Hello,

my code looks like this:
```
import "io" for File

class WebRen {
  construct new() {
     var x = "x"
  }

  write() {
    File.open("communicator.data") {|file|
        file.writeBytes("hello")
    }
  }
}
```

But if I call write(), this error comes up:'
```
operation not permitted
[io line 86] in openWithFlags(_,_,_)
[io line 65] in open(_,_)
```

Does somebody know whats the Error or how to fix it?

Thx.

**Comment by ruby0x1** [comment]
There's no networking in the Wren CLI at the moment.

We'll update the documentation to reflect the latest API, thanks

_note: this issue was moved to the [wren-cli](https://github.com/wren-lang/wren-cli) repository.

**Comment by ruby0x1** [comment]
I don't see anything like system/exec at the moment in the CLI, no.

Here's the documentation for the String class at the language level, where you can find `split`. :) 
https://wren.io/modules/core/string.html#split(separator)

**Comment by hall-of-code** [comment]
Oh haha I have build me yesterday a function to Split 😅.

One Information: The CLI-Documentation can only find in Google, in Wren.io you'll cant find it.
