### ISSUE TITLE
[Enhancement] Unify string indices and search offsets

### ISSUE THREAD

**Issue by guenther-brunthaler** [wren-lang/wren-cli#58]
Currently, Wren considers strings to be UTF-8 strings, which makes array-indexing operations as well as length calculations costly.

For performance reasons, the diverse find/search functions currently do *not* return UTF-8 character indices but rather byte offsets.

This is inconsistent, and also inefficient because obtaining the length of a string is a frequent operation.

My suggestion to this mess would be to *reverse* the current roles of UTF-8- and byte-semantics for strings:

Rather than interpreting strings as UTF-8 by default and providing a method for reinterpreting them as byte arrays, make it the other way around!

That is, all strings would be byte strings by default, just like in Lua.

The find/search functions would then return valid string indices, not just loosely related offsets with no direct connection.

Determining the length of the string would be a cheap operation.

Also, most of the time, strings are just concatenated and not iterated character by character. Such concatenation works with byte strings the same as it does for UTF-8 strings, no changes there necessary in scripts or the Wren implementation.

And if someone really wants to access an UTF-8 string as a character array, a helper method can reinterpret the byte string as an array of UNICODE codepoints or characters.

This would make cheap things the default, and the expensive ones still possible.

Obviously this would break (some) existing code, and would require incrementing the major version number because it is an incompatible chance (assuming wren uses semantic versioning).

Such a change should not be made lightly.

But it *would* unify things and make the search/find functions "good citizens" again.

**Comment by ChayimFriedman2** [comment]
A giant breaking change. If @ruby0x1 agree (I tend to not), we can push it in 0.4.0, maybe.

**Comment by ruby0x1** [comment]
The behavior and reasoning for this is documented here: https://wren.io/modules/core/string.html

The design choice here is intentional, and not going to change at this time.
