### ISSUE TITLE
Argument handling

### ISSUE THREAD

**Issue by WilliamBehrens** [wren-lang/wren-cli#63]
This might have to go to the main Wren repo but is it possible to have a way to get command line arguments passed to a wren script?

**Comment by PureFox48** [comment]
Yes, with Wren-cli, you can recover any command line arguments with code such as this:

``` javascript
import "os" for Process

var args = Process.arguments
```

**Comment by WilliamBehrens** [comment]
Thank you, was unaware of the extra documentation at wren.io/cli/
