### ISSUE TITLE
Would changing shebangs of Python scripts to `python3` upset anyone?

### ISSUE THREAD

**Issue by joshgoebel** [wren-lang/wren-cli#97]
This is constantly tripping me up because python is v2 on my Mac by default.

**Comment by clsource** [comment]
I personally dont mind. They are working only with python3 and hopefully they would be legacy scripts once we can do their job in pure wren 👍

**Comment by ruby0x1** [comment]
it isn't consistent across platforms unfortunately. fixing for you breaks it for me, etc.

**Comment by joshgoebel** [comment]
Ok fingers crossed then:

```
ln -s  /usr/local/bin/python3 /usr/local/bin/python
```
